Handling Missing Data

In [2]:
import pandas as pd

In [23]:
data=pd.read_csv(r"C:\Users\mohan\python\engineering-log\pandas\datasets\missing.csv")

In [24]:
print(data)

   EmployeeID     Name   Age Department   Salary  Experience       City  \
0         101    Alice  25.0         HR  45000.0         2.0      Delhi
1         102      Bob  30.0         IT  60000.0         5.0     Mumbai
2         103  Charlie   NaN    Finance  55000.0         4.0       Pune
3         104    David  28.0         IT      NaN         3.0  Bangalore
4         105      Eva  35.0         HR  70000.0         NaN      Delhi
5         106    Frank  29.0      Sales  50000.0         3.0        NaN
6         107    Grace  31.0    Finance  65000.0         6.0    Chennai
7         108    Henry  27.0         IT      NaN         2.0     Mumbai
8         109      Ivy   NaN      Sales  52000.0         3.0       Pune
9         110     Jack  33.0         HR  72000.0         8.0      Delhi

   Rating
0     4.2
1     4.5
2     4.1
3     4.3
4     NaN
5     3.8
6     4.7
7     NaN
8     4.0
9     4.8

In [5]:
print(data.isnull().sum())

EmployeeID    0
Name          0
Age           2
Department    0
Salary        1
Experience    1
City          1
Rating        2
dtype: int64

Handling Missing Data

In [6]:
data.dropna(inplace=False)

   EmployeeID   Name   Age Department   Salary  Experience     City  Rating
0         101  Alice  25.0         HR  45000.0         2.0    Delhi     4.2
1         102    Bob  30.0         IT  60000.0         5.0   Mumbai     4.5
6         107  Grace  31.0    Finance  65000.0         6.0  Chennai     4.7
9         110   Jack  33.0         HR  72000.0         8.0    Delhi     4.8

Filling Values in missing entries using fillna

In [10]:
data.fillna(9999999,  inplace=False)

,EmployeeID,Name,Age,Department,Salary,Experience,City,Rating
0,101,Alice,25.0,HR,45000.0,2.0,Delhi,4.2
1,102,Bob,30.0,IT,60000.0,5.0,Mumbai,4.5
2,103,Charlie,9999999.0,Finance,55000.0,4.0,Pune,4.1
3,104,David,28.0,IT,9999999.0,3.0,Bangalore,4.3
4,105,Eva,35.0,HR,70000.0,9999999.0,Delhi,9999999.0
5,106,Frank,29.0,Sales,50000.0,3.0,9999999,3.8
6,107,Grace,31.0,Finance,65000.0,6.0,Chennai,4.7
7,108,Henry,27.0,IT,58000.0,2.0,Mumbai,9999999.0
8,109,Ivy,9999999.0,Sales,52000.0,3.0,Pune,4.0
9,110,Jack,33.0,HR,72000.0,8.0,Delhi,4.8

In [22]:
print(data[["Age","Salary"]].fillna(data[["Age","Salary"]].mean(), inplace=False))

     Age        Salary
0  25.00  45000.000000
1  30.00  60000.000000
2  29.75  55000.000000
3  28.00  58555.555556
4  35.00  70000.000000
5  29.00  50000.000000
6  31.00  65000.000000
7  27.00  58000.000000
8  29.75  52000.000000
9  33.00  72000.000000